apiVersion: v1
kind: Service
metadata:
  name: {{ include "tixati.fullname" . }}
  labels:
    {{- include "tixati.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.bittorrentPort }}
      targetPort: bittorrent
      protocol: TCP
      name: bittorrent
  selector:
    {{- include "tixati.selectorLabels" . | nindent 4 }}