apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tixati.fullname" . }}
  labels:
    {{- include "tixati.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tixati.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tixati.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5800
              protocol: TCP
            - name: bittorrent
              containerPort: 8800
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          {{- if .Values.persistence.config.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "tixati.fullname" . }}-config
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: downloads
          {{- if .Values.persistence.downloads.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "tixati.fullname" . }}-downloads
          {{- else }}
          emptyDir: {}
          {{- end }}